[package]
name = "resvg-capi"
version = "0.45.1"
keywords = ["svg", "render", "raster", "c-api"]
edition = "2021"
rust-version = "1.67.1"

[lib]
name = "resvg"
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
resvg = { version = "0.45.1", default-features = false }

[features]
default = ["text", "system-fonts", "memmap-fonts", "raster-images"]
# enables SVG Text support
# adds around 500KiB to your binary
text = ["resvg/text"]
# enables system fonts loading (only for `text`)
system-fonts = ["resvg/system-fonts"]
# enables font files memmaping for faster loading (only for `text`)
memmap-fonts = ["resvg/memmap-fonts"]
raster-images = ["resvg/raster-images"]
capi = []

[package.metadata.capi.header]
generation = false

[package.metadata.capi.install.include]
asset = [{ from = "resvg.h" }]
